parameters:
#    acl.main.example.class: ACL\MainBundle\Example

    acl.main.partner.class: ACL\MainBundle\Entity\Partner
    acl.main.product.class: ACL\MainBundle\Entity\Product
    acl.main.category.class: Application\Sonata\ClassificationBundle\Entity\Category

services:
#    acl.main.example:
#        class: %acl.main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    sonata.media.resizer.custom:
        class: ACL\MainBundle\Resizer\CustomResizer
        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]

    sonata.media.resizer.fixed:
            class: ACL\MainBundle\Resizer\FixedDimensionsResizer
            arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]

    acl.block.service.categories_menu:
        class: ACL\MainBundle\Block\CategoryMenuBlockService
        arguments: [acl.block.service.categories_menu, @templating, @knp_menu.menu_provider, @acl.menu.menu.product_menu_builder]
        tags:
            - { name: sonata.block }

    acl.menu.menu.product_menu_builder:
        class: ACL\MainBundle\Menu\ProductMenuBuilder
        arguments: [@knp_menu.factory, @acl.main.category.manager, @router]


    acl_main.admin.product:
        class: ACL\MainBundle\Admin\ProductAdmin
        arguments: [~, ACL\MainBundle\Entity\Product, ACLMainBundle:ProductAdmin]
        calls:
            - [setPoolFormatter, [@sonata.formatter.pool]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Produto}

    acl_main.admin.brand:
            class: ACL\MainBundle\Admin\BrandAdmin
            arguments: [~, ACL\MainBundle\Entity\Brand, ACLMainBundle:BrandAdmin]
            tags:
                - {name: sonata.admin, manager_type: orm, group: admin, label: Marca}

    acl_main.admin.partner:
        class: ACL\MainBundle\Admin\PartnerAdmin
        arguments: [~, ACL\MainBundle\Entity\Partner, ACLMainBundle:PartnerAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Parceiro}

    acl_main.admin.project:
            class: ACL\MainBundle\Admin\ProjectAdmin
            arguments: [~, ACL\MainBundle\Entity\Project, ACLMainBundle:ProjectAdmin]
            tags:
                - {name: sonata.admin, manager_type: orm, group: admin, label: Case}
    acl_main.admin.trainning:
                class: ACL\MainBundle\Admin\TrainningAdmin
                arguments: [~, ACL\MainBundle\Entity\Trainning, ACLMainBundle:TrainningAdmin]
                tags:
                    - {name: sonata.admin, manager_type: orm, group: admin, label: Treinamento}


    acl.block.service.partners:
        class: ACL\MainBundle\Block\PartnersBlockService
        arguments: [acl.block.service.partners, @templating, @acl.main.partner.manager]
        tags:
            - { name: sonata.block }

    acl.block.service.posts:
        class: ACL\MainBundle\Block\PostsBlockService
        arguments: [acl.block.service.posts, @templating, @sonata.news.manager.post]
        tags:
            - { name: sonata.block }

    acl.block.service.categories:
        class: ACL\MainBundle\Block\CategoryBlockService
        arguments: [acl.block.service.categories, @templating, @sonata.classification.manager.category]
        tags:
            - { name: sonata.block }

    acl.block.service.product:
            class: ACL\MainBundle\Block\ProductBlockService
            arguments: [acl.block.service.product, @templating, @service_container, @acl.main.product.manager]
            tags:
                - { name: sonata.block }

    acl.block.service.richtext:
            class: ACL\MainBundle\Block\RichTextBlockService
            arguments: [acl.block.service.richtext, @templating]
            tags:
                - { name: sonata.block }

    acl.main.partner.manager:
        class: ACL\MainBundle\Entity\PartnerManager
        arguments:
            - %acl.main.partner.class%
            - @doctrine

    acl.main.category.manager:
        class: ACL\MainBundle\Entity\ACLCategoryManager
        arguments:
            - %acl.main.category.class%
            - @doctrine

    acl.main.product.manager:
            class: ACL\MainBundle\Entity\ProductManager
            arguments:
                - %acl.main.product.class%
                - @doctrine
    acl.main.project_repository:
            class: Doctrine\ORM\EntityRepository
            factory_service: doctrine.orm.default_entity_manager
            factory_method: getRepository
            arguments:
                - ACL\MainBundle\Entity\Project

#    acl.main.form.contact:
#      class: ACL\MainBundle\Form\ContactType
#      tags:
#        - name: form.type
#        - alias: form.contact
