parameters:
#    acl.main.example.class: ACL\MainBundle\Example

services:
#    acl.main.example:
#        class: %acl.main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
