parameters:
#    acl.main.example.class: ACL\MainBundle\Example

    acl.main.partner.class: ACL\MainBundle\Entity\Partner
    acl.main.product.class: ACL\MainBundle\Entity\Product
    acl.main.category.class: Application\Sonata\ClassificationBundle\Entity\Category

services:
#    acl.main.example:
#        class: %acl.main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    acl.block.service.categories_menu:
        class: ACL\MainBundle\Block\CategoryMenuBlockService
        arguments: [acl.block.service.categories_menu, @templating, @knp_menu.menu_provider, @acl.menu.menu.product_menu_builder]
        tags:
            - { name: sonata.block }

    acl.menu.menu.product_menu_builder:
        class: ACL\MainBundle\Menu\ProductMenuBuilder
        arguments: [@knp_menu.factory, @acl.main.category.manager, @router]


    acl_main.admin.product:
        class: ACL\MainBundle\Admin\ProductAdmin
        arguments: [~, ACL\MainBundle\Entity\Product, ACLMainBundle:ProductAdmin]
        calls:
            - [setPoolFormatter, [@sonata.formatter.pool]]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Produto}

    acl_main.admin.partner:
        class: ACL\MainBundle\Admin\PartnerAdmin
        arguments: [~, ACL\MainBundle\Entity\Partner, ACLMainBundle:PartnerAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Parceiro}


    acl.block.service.partners:
        class: ACL\MainBundle\Block\PartnersBlockService
        arguments: [acl.block.service.partners, @templating, @acl.main.partner.manager]
        tags:
            - { name: sonata.block }

    acl.block.service.posts:
        class: ACL\MainBundle\Block\PostsBlockService
        arguments: [acl.block.service.posts, @templating, @sonata.news.manager.post]
        tags:
            - { name: sonata.block }

    acl.block.service.categories:
        class: ACL\MainBundle\Block\CategoryBlockService
        arguments: [acl.block.service.categories, @templating, @sonata.classification.manager.category]
        tags:
            - { name: sonata.block }




    acl.main.partner.manager:
        class: ACL\MainBundle\Entity\PartnerManager
        arguments:
            - %acl.main.partner.class%
            - @doctrine

    acl.main.category.manager:
        class: ACL\MainBundle\Entity\ACLCategoryManager
        arguments:
            - %acl.main.category.class%
            - @doctrine

    acl.main.product.manager:
            class: ACL\MainBundle\Entity\ProductManager
            arguments:
                - %acl.main.product.class%
                - @doctrine