sonata_classification:
  admin:
    category:
      class: Application\Sonata\ClassificationBundle\Admin\CategoryAdmin
parameters:
  sonata.classification.manager.category.class: Application\Sonata\ClassificationBundle\Entity\CategoryManager