<?php

namespace ACL\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    public function findAllWithMedia(){
        $qb = $this->createQueryBuilder('p')
            ->select('p, i')
            ->leftJoin('p.image', 'i');
        return $qb->getQuery()->execute();
    }

}
